import type { CompileCssOptions, CompileJsonOptions, MoDocument, MoTokenMap, MoTokenValue } from './types.js';

const kebab = (value: string) => value
  .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
  .replace(/[^a-zA-Z0-9]+/g, '-')
  .replace(/^-+|-+$/g, '')
  .toLowerCase();

const cssName = (path: string[]) => `--mo-${path.map(kebab).filter(Boolean).join('-')}`;

const referencePath = (ref: string): string[] | undefined => {
  const normalized = ref.startsWith('#/tokens/') ? ref.slice('#/tokens/'.length) : ref.startsWith('$') ? ref.slice(1) : undefined;
  return normalized ? normalized.split(/[./]/).filter(Boolean) : undefined;
};

const toCssValue = (value: MoTokenValue, resolveReferences: boolean): string => {
  if (Array.isArray(value)) return value.map((item) => toCssValue(item, resolveReferences)).join(' ');
  if (typeof value === 'object' && value !== null && !Array.isArray(value) && '$ref' in value) {
    const ref = (value as { $ref?: unknown }).$ref;
    if (typeof ref !== 'string') return String(value);
    const path = referencePath(ref);
    if (!resolveReferences || !path) return ref;
    return path.length ? `var(${cssName(path)})` : ref;
  }
  return String(value);
};

const flatten = (value: MoTokenValue, path: string[], out: Array<[string[], MoTokenValue]>) => {
  if (typeof value === 'object' && value !== null && !Array.isArray(value) && !('$ref' in value)) {
    for (const [key, child] of Object.entries(value as Record<string, MoTokenValue>)) flatten(child, [...path, key], out);
  } else {
    out.push([path, value]);
  }
};

export const compileMoToCss = (document: MoDocument, options: CompileCssOptions = {}): string => {
  const selector = options.selector ?? ':root';
  const includeComments = options.includeComments ?? true;
  const resolveReferences = options.resolveReferences ?? true;
  const entries: Array<[string[], MoTokenValue]> = [];
  for (const [key, value] of Object.entries(document.tokens)) flatten(value, [key], entries);
  for (const [componentName, component] of Object.entries(document.components ?? {})) {
    for (const [key, value] of Object.entries(component.tokens ?? {})) flatten(value, ['component', componentName, key], entries);
    for (const [stateName, state] of Object.entries(component.states ?? {})) {
      for (const [key, value] of Object.entries(state.tokens ?? {})) flatten(value, ['component', componentName, stateName, key], entries);
    }
  }
  const lines = [includeComments ? `/* Generated by moho-design from ${document.name}.mo */` : '', `${selector} {`].filter(Boolean);
  for (const [path, value] of entries) lines.push(`  ${cssName(path)}: ${toCssValue(value, resolveReferences)};`);
  lines.push('}');
  return `${lines.join('\n')}\n`;
};

export const compileMoToJson = (document: MoDocument, options: CompileJsonOptions = {}): string =>
  JSON.stringify(document, null, options.pretty === false ? 0 : 2) + '\n';

export const getCssVariableName = (...path: string[]) => cssName(path);
